version: '3'
services:
  postgresql:
    image: postgres:14
    command: postgres -c 'max_connections=250'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: b2b_merchant_service_db